version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sglinkbackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r7zcdn0zw33w"
s3_prefix = "sglinkbackend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
