AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MyWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stephangaskill.link
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  VisitCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitCounter
      AttributeDefinitions:
        -
          AttributeName: 'visits'
          AttributeType: 'S'
      KeySchema:
        - 
          AttributeName: 'visits'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '2'
        WriteCapacityUnits: '2'

  VisitsLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: visitCounter
      CodeUri: sglink/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /visit
            Method: post